### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by skorunka** [ondrejnov/eet#39]
I'm using PlayGround WSDL and provided test certificates. Any idea? Thank you.

**Comment by daddyy** [comment]
Where's your problem have you got some report from log? or can you send your request?

**Comment by Pomezny** [comment]
You need to import trusted certificate issuers to your PHP stack. If you are using xampp solution is here: http://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate If not problem is same but solution different. Root of the problem is that your server cannot verify issuer of GFŘS certificate and you need to suply root issuers bundle to your php environment

**Comment by skorunka** [comment]
Sorted bz installing lates open%ssl.
